#ifndef ORGOMGC4IDOMAIN_MODELNAVIGATION_DOMAINDEPTHDEFVAR
#define ORGOMGC4IDOMAIN_MODELNAVIGATION_DOMAINDEPTHDEFVAR
#include "Common_Types.idl"
#include "Coordinates_and_Positions.idl"
#include "org__omg__c4i__Domain_Model__Navigation_Domain.idl"
#include "org__omg__c4i__Domain_Model__Navigation_Domain__Reporting.idl"

module org
{

  module omg
  {

    module c4i
    {

      module Domain_Model
      {

        module Navigation_Domain
        {

          @doc("This package contains classes to model of the depth of water the platform may be \
            in. ")
          module Depth
          {

            @doc("Measured positive down in metres. c.f. altitude_coordinate_type in OARIS \
                Common_Types package.")
            typedef double depth_coordinate_type;

            @doc("The accuracy of the platform's depth report")
            struct depth_accuracy_type
            {
              @doc("The provenance or method by which the accuracy values have been derived")
              org::omg::c4i::Domain_Model::Navigation_Domain::accuracy_derivation_type derivation;
              @doc("The accuracy (represented as one standard deviation) of the time value.")
              org::omg::c4i::Domain_Model::Common_Types::Coordinates_and_Positions::duration_type time_accuracy;
              @doc("The accuracy of the keel depth measurement.")
              @optional depth_coordinate_type keel_depth;
              @doc("The accuracy of the depth below keel measurement.")
              @optional depth_coordinate_type depth_below_keel;
              @doc("The accuracy of the water depth measurement.")
              @optional depth_coordinate_type water_depth;
            };

            @doc("Used by waterborne craft to report depth information.")
            struct depth_report_type
            {
              @doc("The generic type of navigation system used.")
              org::omg::c4i::Domain_Model::Navigation_Domain::navigation_derivation_kind_type system_kind;
              @doc("An optional set of contributing sensor kinds that have been used to derive the \
                report. This set is defined when the system_kind is COMPOSITE.")
              org::omg::c4i::Domain_Model::Navigation_Domain::Reporting::navigation_report_composite_contributors_type composite_contributors;
              @doc("The specific system employed - e.g. GPS, LORAN-B")
              org::omg::c4i::Domain_Model::Navigation_Domain::Reporting::navigation_report_specific_system_type specific_system;
              @doc("Whether the information has been simulated - e.g. for operator training.")
              @key boolean simulated;
              @doc("The time for which the report values are valid.")
              org::omg::c4i::Domain_Model::Common_Types::time_type time_of_information;
              @doc("The depth of the keel below the surface of the water.")
              @optional depth_coordinate_type keel_depth;
              @doc("The depth of the bed below the keel.")
              @optional depth_coordinate_type depth_below_keel;
              @doc("The depth of the bed below the water's surface.")
              @optional depth_coordinate_type water_depth;
              @doc("The accuracy of each depth measurement")
              depth_accuracy_type accuracy;
            };
          };
        };
      };
    };
  };
};
#endif
