#ifndef ORGOMGC4IDOMAIN_MODELNAVIGATION_DOMAINATTITUDEOFFSET_REPORTDEFVAR
#define ORGOMGC4IDOMAIN_MODELNAVIGATION_DOMAINATTITUDEOFFSET_REPORTDEFVAR
#include "org__omg__c4i__Domain_Model__Navigation_Domain__Attitude.idl"
#include "org__omg__c4i__Domain_Model__Navigation_Domain__Attitude__Ext.idl"

module org
{

  module omg
  {

    module c4i
    {

      module Domain_Model
      {

        module Navigation_Domain
        {

          module Attitude
          {

            // Additional classes supporting generalisation offset_report_type.
            module Offset_Report
            {

              // Union of specialisations options for keys to classes based on generalisation offset_report_type.
              union offset_report_union_key_type switch (offset_report_key_kind_type)
              {
                case ATTITUDE_ROTATION : org::omg::c4i::Domain_Model::Navigation_Domain::Attitude::attitude_rotation_key_type attitude_rotation_key;
                case ATTITUDE_ROTATION_RATE : org::omg::c4i::Domain_Model::Navigation_Domain::Attitude::Ext::attitude_rotation_rate_key_type attitude_rotation_rate_key;
                case POSITION_OFFSET : org::omg::c4i::Domain_Model::Navigation_Domain::Attitude::Ext::position_offset_key_type position_offset_key;
                case VELOCITY_OFFSET : org::omg::c4i::Domain_Model::Navigation_Domain::Attitude::Ext::velocity_offset_key_type velocity_offset_key;
              };

            };
          };
        };
      };
    };
  };
};
#endif
